rootPageId: 1
base: /
baseVariants: { }
languages:
-
  title: English
  enabled: true
  languageId: '0'
  base: /en/
  typo3Language: default
  locale: en_US.UTF-8
  iso-639-1: en
  navigationTitle: ''
  hreflang: ''
  direction: ''
  flag: en-us-gb
-
  title: German
  enabled: true
  languageId: '1'
  base: /de/
  typo3Language: de
  locale: de_DE.UTF-8
  iso-639-1: de
  navigationTitle: ''
  hreflang: ''
  direction: ''
  fallbackType: strict
  flag: de
errorHandling: { }
routes: { }
